before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - "bundle exec rake db:migrate"
language: ruby
rvm:
  - 2.1.5
  - 2.1.0
  - 1.9.3
addons:
  postgresql: '9.3'
cache: bundler
script: bundle exec rake
